# Randomized and Extract Data

In [ ]:
# RANDOMIZED THE DATASET AND TAKE THE FIRST 1000 rows

import pandas as pd

# 1. Load the original dataset
df = pd.read_csv("Tugas Akhir_Dataset_Merged_Original - v1.0_data processing.csv")

# 2. Randomize the dataset (shuffle all rows)
df_randomized = df.sample(frac=1, random_state=42).reset_index(drop=True)

# 3. Save the randomized dataset to a new file
df_randomized.to_csv("tweets_randomized v1.1.csv", index=False)

# 4. Extract the first 1000 rows from the randomized dataset
df_sample = df_randomized.head(3000)

# 5. Save the sample of 1000 tweets
df_sample.to_csv("tweets_sample_3000 v1.0.csv", index=False)

print("Randomized dataset saved as 'tweets_randomized.csv'")
print("Sample of 1000 tweets saved as 'tweets_sample_1000.csv'")

In [ ]:
import pandas as pd

# 1. Load the original dataset
df = pd.read_csv("Tugas Akhir_Dataset_Merged_Original - v1.0_data processing.csv")

In [ ]:
import pandas as pd

# Load your dataset
df = pd.read_csv("tweets_sample_1000.csv")

# Define your regex pattern for relevant keywords
pattern = r"transjakarta|busway|tj"

# Filter to get tweets that do NOT contain any of the keywords
df_irrelevant = df[~df["full_text"].str.contains(pattern, case=False, na=False)]

# Preview the first few irrelevant tweets
print("Irrelevant Tweets:")
print(df_irrelevant.head())

Irrelevant Tweets:
    conversation_id_str             created_at_original  favorite_count  \
4          1.835020e+18  Sat Sep 14 18:10:42 +0000 2024               2
9          1.819300e+18  Fri Aug 02 09:12:15 +0000 2024               3
33         1.814620e+18  Sat Jul 20 11:27:25 +0000 2024               2
34         1.847830e+18  Sun Oct 20 02:22:09 +0000 2024               2
46         1.808770e+18  Thu Jul 04 07:47:08 +0000 2024              12

                                            full_text        id_str  \
4                                        DURANNNNNNN   1.835020e+18
9   apa itu lagu-lagu Jeketi Jusi Lusi lahhh https...  1.819300e+18
33           JAK 71 KWK-1695. https://t.co/r4k718yNig  1.814620e+18
34  Pada hari ini Minggu (20/10/2024) sejumlah ope...  1.847830e+18
46  Next target: mengurangi ketergantungan painkil...  1.808770e+18

                                          image_url in_reply_to_screen_name  \
4                                               NaN                     NaN
9   https://pbs.twimg.com/media/GT9zwFzb0AEbrkc.jpg                     NaN
33  https://pbs.twimg.com/media/GS7WIP1bIAEkCE2.jpg                     NaN
34                                              NaN                     NaN
46  https://pbs.twimg.com/media/GRoKQhoagAA09Wj.jpg                     NaN

   lang       location  quote_count  reply_count  retweet_count  \
4    in        London             0            1              0
9    in            NaN            1            0              0
33   in  Priority Seat            0            1              0
34   in        Jakarta            1            0              0
46   in  Priority Seat            0            1              0

                                            tweet_url  user_id_str   username  \
4      https://x.com/TJ45_/status/1835018351006941492  249725326.0      TJ45_
9    https://x.com/initije/status/1819300167545508079  580853610.0    initije
33  https://x.com/26Ceicei/status/1814623139244224863  124639815.0   26Ceicei
34  https://x.com/kompascom/status/184782560503710...   23343960.0  kompascom
46  https://x.com/26Ceicei/status/1808769499015131155  124639815.0   26Ceicei

   created_at_formated  Unnamed: 16
4        9/14/24 18:10          NaN
9          8/2/24 9:12          NaN
33       7/20/24 11:27          NaN
34       10/20/24 2:22          NaN
46         7/4/24 7:47          NaN

In [ ]:
import pandas as pd

# Load the original tweets DataFrame
df_original = pd.read_csv("tweets_sample_1000_filtered 1.0.csv")

# Load or use your DataFrame with irrelevant tweets (df_irrelevant)
# For this example, assume df_irrelevant already exists

# Remove tweets from df_original that are present in df_irrelevant
df_cleaned = df_original[~df_original["full_text"].isin(df_irrelevant["full_text"])]

# Preview the cleaned DataFrame
print("Cleaned DataFrame:")
print(df_cleaned.head())

# Optionally, save the cleaned DataFrame
df_cleaned.to_csv("tweets_cleaned.csv", index=False)

Cleaned DataFrame:
   conversation_id_str             created_at_original  favorite_count  \
0         1.850000e+18  Fri Oct 25 18:06:07 +0000 2024               1
1         1.820000e+18  Mon Aug 05 03:53:41 +0000 2024               0
2         1.870000e+18  Mon Dec 16 05:35:43 +0000 2024               0
3         1.820000e+18  Mon Aug 05 03:44:03 +0000 2024               0
4         1.810000e+18  Fri Jul 19 23:01:31 +0000 2024               0

                                           full_text        id_str  \
0  Kantongi Tender 20 Bus Listrik Transjakarta VK...  1.850000e+18
1  Hari ini mata berasa pedih bet kena AC terus g...  1.820000e+18
2  Pertama kali naik busway nanya ke nyokap soaln...  1.870000e+18
3                            FUCK HELLO(:?5?5?3 4 tj  1.820000e+18
4  Hari ini ada we the fest kalau naik busway dr ...  1.810000e+18

                                         image_url in_reply_to_screen_name  \
0                                              NaN                     NaN
1                                              NaN                     NaN
2  https://pbs.twimg.com/media/Ge5ag0ZaIAA-smp.jpg                     NaN
3                                              NaN                     NaN
4                                              NaN                     NaN

  lang                        location  quote_count  reply_count  \
0   in          Jakarta Capital Region            0            0
1   in  Scuderia Ferrari HQ, Maranello            0            0
2   in                             NaN            0            1
3   sv                   freepalestine            0            0
4   in                             NaN            0            0

   retweet_count                                          tweet_url  \
0              0  https://x.com/idx_channel/status/1849875100335...
1              0  https://x.com/frz_nnda/status/1820307159365697564
2              0  https://x.com/sumberdaye/status/18685304243704...
3              0  https://x.com/triviafever/status/1820304734861...
4              0  https://x.com/biforsytheIII/status/18144354279...

    user_id_str       username created_at_formated  Unnamed: 16
0  4.755285e+09    idx_channel    10/25/2024 18:06          NaN
1  1.948948e+08       frz_nnda       8/5/2024 3:53          NaN
2  1.250000e+18     sumberdaye     12/16/2024 5:35          NaN
3  1.640000e+18    triviafever       8/5/2024 3:44          NaN
4  1.080000e+18  biforsytheIII     7/19/2024 23:01          NaN

# Data Cleaning

In [18]:
import pandas as pd
import re

def clean_tweet(text):
    """
    Clean a tweet by removing URLs, mentions, hashtags, special characters, and extra whitespace.
    """
    # Remove URLs (http, https, www)
    text = re.sub(r'http\S+|www\.\S+', '', text)
    
    # Remove Twitter handles (@username)
    text = re.sub(r'@\w+', '', text)
    
    # Remove '#' from hashtags (you can choose to remove the whole hashtag if needed)
    text = re.sub(r'#', '', text)
    
    # Optionally, remove numbers and punctuation
    # Here, we remove any character that is not a letter or whitespace.
    text = re.sub(r'[^A-Za-z\s]', '', text)
    
    # Convert to lowercase
    text = text.lower()
    
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

if __name__ == "__main__":
    # Load your CSV file
    df = pd.read_csv("ready v1.0/tweets_ready_to_be_cleaned v1.0.csv")
    
    # Create a new column 'original_tweet' to store the original text (copy of 'full_text')
    # df["ori_tweet"] = df["full_text"]
    
    # Apply the cleaning function to create a 'cleaned_full_text' column
    df["cleaned_full_text"] = df["full_text"].apply(clean_tweet)
    
    # Preview the DataFrame to see both columns side by side
    # print(df[["original_tweet", "cleaned_full_text"]].head())
    
    # Optionally, save the updated DataFrame to a new CSV file
    df.to_csv("ready v1.0/tweets_ready_to_be_labeled v1.0.csv", index=False)

AttributeError: module 'numpy' has no attribute 'matrix'

In [ ]:
# Version 1.0

import csv
import re

def clean_tweet(text):
    """
    Clean a tweet by removing URLs, mentions, hashtags, special characters, and extra whitespace.
    """
    # Remove URLs (http, https, www)
    text = re.sub(r'http\S+|www\.\S+', '', text)
    
    # Remove Twitter handles (@username)
    text = re.sub(r'@\w+', '', text)
    
    # Remove '#' from hashtags (you can choose to remove the whole hashtag if needed)
    text = re.sub(r'#', '', text)
    
    # Remove any character that is not a letter or whitespace
    text = re.sub(r'[^A-Za-z\s]', '', text)
    
    # Convert to lowercase
    text = text.lower()
    
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

# Define input and output file paths
input_file = "ready v1.0/tweets_ready_to_be_cleaned v1.0.csv"
output_file = "ready v1.0/tweets_ready_to_be_labeled v1.0.csv"

# Open the input CSV file and read its content
with open(input_file, newline='', encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    # Prepare fieldnames: add new columns "original_tweet" and "cleaned_full_text"
    fieldnames = reader.fieldnames + ["original_tweet", "cleaned_full_text"]
    
    # Create a list to hold the updated rows
    updated_rows = []
    for row in reader:
        # Save the original tweet text (assuming the column is named "full_text")
        row["original_tweet"] = row["full_text"]
        # Clean the tweet and store it in the new column
        row["cleaned_full_text"] = clean_tweet(row["full_text"])
        updated_rows.append(row)

# Write the updated rows to the output CSV file
with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(updated_rows)

print("File processed and saved to", output_file)

File processed and saved to ready v1.0/tweets_ready_to_be_labeled v1.0.csv

In [2]:
# Version 1.1

import csv
import re
import string

def clean_tweet(text):
    """
    Clean a tweet by:
    - Removing URLs.
    - Removing only the '@' symbol from mentions (keeping the account name).
    - Removing the '#' symbol from hashtags (keeping the hashtag text).
    - Removing special characters (keeping alphanumeric characters, punctuation, and whitespace).
    - Converting text to lowercase.
    - Removing extra whitespace.
    """
    # Remove URLs (http, https, www)
    text = re.sub(r'http\S+|www\.\S+', '', text)
    
    # Remove only the '@' symbol (leaving the username intact)
    text = re.sub(r'@', '', text)
    
    # Remove '#' from hashtags (keep the hashtag text)
    text = re.sub(r'#', '', text)
    
    # Remove special characters but keep punctuation.
    # Build a set of allowed characters: letters, digits, punctuation, and whitespace.
    allowed_chars = string.ascii_letters + string.digits + string.punctuation + " "
    # Create a regex pattern that matches any character NOT in the allowed set.
    pattern = f"[^{re.escape(allowed_chars)}]"
    text = re.sub(pattern, '', text)
    
    # Convert to lowercase
    text = text.lower()
    
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

# Define input and output file paths
input_file = "data TJ google playstore/play.csv"
output_file = "data TJ google playstore/play_ready to be labelled.csv"

# Open the input CSV file and read its content
with open(input_file, newline='', encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    # Prepare fieldnames: add new columns "original_tweet" and "cleaned_full_text"
    fieldnames = reader.fieldnames + ["original_tweet", "cleaned_full_text"]
    
    # Create a list to hold the updated rows
    updated_rows = []
    for row in reader:
        # Save the original tweet text (assuming the column is named "full_text")
        row["original_tweet"] = row["full_text"]
        # Clean the tweet and store it in the new column
        row["cleaned_full_text"] = clean_tweet(row["full_text"])
        updated_rows.append(row)

# Write the updated rows to the output CSV file
with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(updated_rows)

print("File processed and saved to", output_file)

File processed and saved to data TJ google playstore/play_ready to be labelled.csv

In [ ]:
# version 1.2

import csv
import re
import string
import html

def clean_tweet(text):
    """
    Clean a tweet by applying the following transformations:
    - Remove URLs (starting with http, https, www).
    - Remove all emoji.
    - Unescape HTML entities (e.g., '&amp;' becomes '&').
    - Remove all non-ASCII characters (to eliminate any weird characters).
    - Process mentions: keep only the mention for 'pt_transjakarta' (standardized to lower-case) and remove all others.
    - Remove the '#' symbol from hashtags (keeping the hashtag text).
    - Separate every punctuation mark from adjacent characters with whitespace.
    - Separate the Indonesian prefix 'di' from the main word (case-insensitive).
    - Separate the Indonesian suffix 'nya' from the main word (case-insensitive).
    - Separate letters and numbers if they are attached (e.g., 'k13' becomes 'k 13'), while leaving pure numbers unchanged.
    - Replace the word 'jaklingko' with 'angkutan'.
    - Remove extra whitespace.
    - Leave the original casing (do not lowercase the entire tweet, except for ensuring pt_transjakarta is standardized).
    """

    # --- Remove URLs ---
    text = re.sub(r'http\S+|www\.\S+', '', text)
    
    # --- Remove Emoji ---
    emoji_pattern = re.compile(
        "[" 
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        "]+", flags=re.UNICODE)
    text = emoji_pattern.sub(r'', text)
    
    # --- Unescape HTML entities ---
    text = html.unescape(text)
    
    # --- Remove all non-ASCII characters (i.e. weird characters) ---
    text = re.sub(r'[^\x00-\x7F]+', '', text)
    
    # --- Process mentions: Remove all mentions except for '@pt_transjakarta'
    def replace_mention(match):
        mention = match.group(1)
        if mention.lower() == "pt_transjakarta":
            return "pt_transjakarta"  # standardize to lower-case for pt_transjakarta
        else:
            return ""  # remove other mentioned accounts
    text = re.sub(r'@(\w+)', replace_mention, text)
    
    # --- Process hashtags: Remove '#' symbol (keeping the hashtag text)
    text = re.sub(r'#', '', text)
    
    # --- Separate punctuation from adjoining characters ---
    text = re.sub(r'([{}])'.format(re.escape(string.punctuation)), r' \1 ', text)
    text = re.sub(r'\s+', ' ', text).strip()  # normalize whitespace
    
    # --- Separate the prefix "di" from the main word (handles both 'di' and 'Di')
    text = re.sub(r'\b([dD]i)([A-Za-z]+)', r'\1 \2', text)
    
    # --- Separate the suffix "nya" from the main word (case-insensitive) ---
    text = re.sub(r'([A-Za-z]+)(nya)\b', r'\1 \2', text, flags=re.IGNORECASE)
    
    # --- Separate letters and numbers attached ---
    text = re.sub(r'([A-Za-z])(\d+)', r'\1 \2', text)
    text = re.sub(r'(\d+)([A-Za-z])', r'\1 \2', text)
    
    # --- Replace the word 'jaklingko' with 'angkutan' ---
    text = re.sub(r'\bjaklingko\b', 'angkutan', text, flags=re.IGNORECASE)
    
    # --- Final cleanup: Remove any extra whitespace ---
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

# Define input and output file paths
input_file = "ready v1.0/PRDECT-ID Dataset v1.0_RAW.csv"
output_file = "ready v1.0/PRDECT-ID Dataset v1.0_READY TO BE LABELED.csv"

# Open the input CSV file and read its content
with open(input_file, newline='', encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    # Prepare fieldnames by adding new columns "original_tweet" and "cleaned_full_text"
    fieldnames = reader.fieldnames + ["original_tweet", "cleaned_full_text"]
    
    # Create a list to hold the updated rows
    updated_rows = []
    for row in reader:
        # Save the original tweet text (assuming the column is named "full_text")
        row["original_tweet"] = row["full_text"]
        # Clean the tweet and store the result in the new column
        row["cleaned_full_text"] = clean_tweet(row["full_text"])
        updated_rows.append(row)

# Write the updated rows to the output CSV file
with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(updated_rows)

print("File processed and saved to", output_file)

File processed and saved to ready v1.0/PRDECT-ID Dataset v1.0_READY TO BE LABELED.csv

In [1]:
# version 1.3

import csv
import re
import string
import html

def clean_tweet(text):
    """
    Clean a tweet by applying the following transformations:
    - Remove URLs (starting with http, https, www).
    - Remove all emoji.
    - Unescape HTML entities (e.g., '&amp;' becomes '&').
    - Remove all non-ASCII characters (to eliminate any weird characters).
    - Process mentions: keep only the mention for 'pt_transjakarta' (standardized to lower-case) and remove all others.
    - Remove the '#' symbol from hashtags (keeping the hashtag text).
    - Separate every punctuation mark (except underscore) from adjacent characters with whitespace.
    - Separate the Indonesian prefix 'di' from the main word (case-insensitive).
    - Separate the Indonesian suffix 'nya' from the main word (case-insensitive).
    - Separate letters and numbers if they are attached (e.g., 'k13' becomes 'k 13'), while leaving pure numbers unchanged.
    - Replace the word 'jaklingko' with 'angkutan'.
    - Remove extra whitespace.
    - Leave the original casing (do not lowercase the entire tweet, except for ensuring pt_transjakarta is standardized).
    """
    
    # --- Remove URLs ---
    text = re.sub(r'http\S+|www\.\S+', '', text)
    
    # --- Remove Emoji ---
    emoji_pattern = re.compile(
        "[" 
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        "]+", flags=re.UNICODE)
    text = emoji_pattern.sub(r'', text)
    
    # --- Unescape HTML entities ---
    text = html.unescape(text)
    
    # --- Remove all non-ASCII characters (i.e. weird characters) ---
    text = re.sub(r'[^\x00-\x7F]+', '', text)
    
    # --- Process hashtags: Remove '#' symbol (keeping the hashtag text)
    text = re.sub(r'#\w+', '', text)
    
    # --- Process mentions: Keep @pt_transjakarta as 'pt_transjakarta', remove all other @mentions ---
    def process_mentions(match):
        mention = match.group(0)
        if mention.lower() == '@pt_transjakarta':
            return 'pt_transjakarta'
        else:
            return ''
    
    text = re.sub(r'@\w+', process_mentions, text, flags=re.IGNORECASE)
    
    # --- Separate punctuation from adjoining characters (exclude underscore) ---
    # Remove underscore from punctuation set
    punct_no_underscore = string.punctuation.replace('_', '')
    text = re.sub(r'([{}])'.format(re.escape(punct_no_underscore)), r' \1 ', text)
    text = re.sub(r'\s+', ' ', text).strip()  # normalize whitespace
    
    # --- Final cleanup: Remove any extra whitespace ---
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

# Define input and output file paths
# input_file = "../../Production/twitterapi IO/self_training/batch 7 8 9.csv"
# output_file = "../../Production/twitterapi IO/self_training/self_training_batch 7 8 9-Ready to be Labeled.csv"

input_file = "../../Production/twitterapi IO/Proof of Concept/POC_Merged_deduplicated_keyword filtered.csv"
output_file = "../../Production/twitterapi IO/Proof of Concept/POC_Merged_deduplicated_keyword filtered_cleaned.csv"

# Open the input CSV file and read its content
with open(input_file, newline='', encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    # Prepare fieldnames by adding new columns "original_tweet" and "cleaned_full_text"
    fieldnames = reader.fieldnames + ["original_tweet", "cleaned_full_text"]
    
    # Create a list to hold the updated rows
    updated_rows = []
    for row in reader:
        # Save the original tweet text (assuming the column is named "full_text")
        row["original_tweet"] = row["full_text"]
        # Clean the tweet and store the result in the new column
        row["cleaned_full_text"] = clean_tweet(row["full_text"])
        updated_rows.append(row)

# Write the updated rows to the output CSV file
with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(updated_rows)

print("File processed and saved to", output_file)

File processed and saved to ../../Production/twitterapi IO/Proof of Concept/POC_Merged_deduplicated_keyword filtered_cleaned.csv

# Filtered from main dataset

In [2]:
import pandas as pd

# Path file
big_csv_path = 'data filtering 1.2/Tugas Akhir_Dataset_Merged_Original - v1.0_data processing_to be Labeled.csv'
ori_txt_path = 'data filtering 1.2/ori.txt'
output_csv_path = 'data filtering 1.2/Tugas Akhir_Dataset_Merged_Original - v1.0_data processing_to be Labeled_filtered.csv'

# Baca CSV besar
df = pd.read_csv(big_csv_path)

# Baca ori.txt dan kumpulkan teks sebelum delimiter '#### #### ####'
texts_to_remove = set()
with open(ori_txt_path, 'r', encoding='utf-8') as f:
    for line in f:
        text = line.split('#### #### ####')[0].strip()
        if text:
            texts_to_remove.add(text)

# Filter DataFrame
filtered_df = df[~df['cleaned_full_text'].isin(texts_to_remove)].copy()

# Simpan hasil
filtered_df.to_csv(output_csv_path, index=False)

print(f"Total baris awal : {len(df)}")
print(f"Baris dihapus     : {len(df) - len(filtered_df)}")
print(f"Total baris akhir : {len(filtered_df)}")

Total baris awal : 8332
Baris dihapus     : 616
Total baris akhir : 7716

# Filtering the Dataset from Unrelevant Tweets

In [ ]:
# FILTER ONLY SHOWS TWEETS THAT DOES NOT HAVE ANY OF THESE WORDS (TJ, Transjakarta, Busway)

import pandas as pd

# Load the dataset
df = pd.read_csv("tweets_sample_2000 v1.0.csv")

# Define the regular expression pattern for the words to exclude
pattern = r"(TJ|Transjakarta|Busway)"

# Reassign df to only include tweets that do NOT contain any of the specified words
df = df[~df['full_text'].str.contains(pattern, case=False, na=False)]

# Now df no longer includes the rows with the excluded words; view it in Data Wrangler/Data Viewer
df

C:\Users\arsya\AppData\Local\Temp\ipykernel_6708\1355227142.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df = df[~df['full_text'].str.contains(pattern, case=False, na=False)]

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
5,1.820000e+18,Fri Aug 16 12:58:13 +0000 2024,0,Perugia Italia,1.820000e+18,NaN,NaN,in,"Perugia, Umbria",0,0,0,https://x.com/fabbro94_tj/status/1824430461977...,4.165014e+09,fabbro94_tj,8/16/2024 12:58,NaN
15,1.840000e+18,Fri Sep 20 04:50:53 +0000 2024,0,kapolsek Tanah Putih Tanjung Melawan IPDA BONN...,1.840000e+18,https://pbs.twimg.com/media/GX5N8G9aUAE-1xY.jpg,NaN,in,"Tanah Putih Tanjung Melawan, I",0,0,0,https://x.com/PolsekTj/status/1836991396001247316,1.270000e+18,PolsekTj,9/20/2024 4:50,NaN
28,1.840000e+18,Tue Sep 17 17:22:46 +0000 2024,1,P2LAN https://t.co/Bna4FGCgsF,1.840000e+18,https://pbs.twimg.com/media/GXsdQP4XEAAN7pu.jpg,NaN,tl,Soweto,0,1,0,https://x.com/TuvaJr/status/1836093451525591511,1.170000e+18,TuvaJr,9/17/2024 17:22,NaN
35,1.870000e+18,Sun Dec 15 13:32:54 +0000 2024,2,Kalau suka atau kangen tuh diusahain. Kayak ak...,1.870000e+18,https://pbs.twimg.com/media/Ge1-JkCaIAEqROd.jpg,NaN,in,Priority Seat,0,0,0,https://x.com/26Ceicei/status/1868288125879132632,1.246398e+08,26Ceicei,12/15/2024 13:32,NaN
43,1.810000e+18,Wed Jul 10 04:59:20 +0000 2024,24,Bismillah yang dateng Bus BRT,1.810000e+18,NaN,NaN,in,Jakarta Capital Region,0,5,8,https://x.com/BuswayFansC/status/1810901595741...,2.394714e+09,BuswayFansC,7/10/2024 4:59,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1947,1.840000e+18,Thu Sep 19 19:29:54 +0000 2024,0,Lamine Yamal ️,1.840000e+18,NaN,NaN,in,"Akure, Nigeria",0,0,0,https://x.com/Shizzy_tj/status/183685022136574...,7.820000e+17,Shizzy_tj,9/19/2024 19:29,NaN
1954,1.820000e+18,Wed Aug 14 09:26:21 +0000 2024,0,Klantink,1.820000e+18,NaN,NaN,lt,"Helsinki, Finland",0,0,0,https://x.com/alfatj_/status/1823652370016035289,2.524144e+09,alfatj_,8/14/2024 9:26,NaN
1970,1.830000e+18,Fri Aug 23 20:38:16 +0000 2024,5,Xabi time,1.830000e+18,NaN,NaN,in,Soweto,0,2,1,https://x.com/TuvaJr/status/1827082954771922980,1.170000e+18,TuvaJr,8/23/2024 20:38,NaN
1976,1.820000e+18,Fri Aug 02 20:13:34 +0000 2024,1,YUJI NISHIDA IS HIM!!!!!!!!,1.820000e+18,NaN,NaN,in,142208,0,0,0,https://x.com/yukicoded/status/181946659279705...,1.670000e+18,yukicoded,8/2/2024 20:13,NaN
1999,1.820000e+18,Sun Aug 04 14:25:36 +0000 2024,9,Gedung Filateli Jakarta yang kini berganti nam...,1.820000e+18,https://pbs.twimg.com/media/GUJOwAYbwAADzoS.jpg,NaN,in,Priority Seat,0,1,1,https://x.com/26Ceicei/status/1820103799044030842,1.246398e+08,26Ceicei,8/4/2024 14:25,NaN

In [ ]:
# FILTER OUT TWEETS THAT DOES NOT HAVE ANY OF THESE WORDS (TJ, Transjakarta, Busway)

import pandas as pd

# Load the dataset
df = pd.read_csv("tweets_sample_2000 v1.0.csv")

# Define the regular expression pattern for the words to include
pattern = r"(TJ|Transjakarta|Busway)"

# Reassign df to only include tweets that contain at least one of the specified words
df = df[df['full_text'].str.contains(pattern, case=False, na=False)]

# Now df only contains tweets that have the words "TJ", "Transjakarta", or "Busway"
df

C:\Users\arsya\AppData\Local\Temp\ipykernel_6708\903427851.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df = df[df['full_text'].str.contains(pattern, case=False, na=False)]

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
0,1.860000e+18,Sun Dec 01 14:34:21 +0000 2024,2,@PT_Transjakarta jadi buat besok kalau naik dr...,1.860000e+18,NaN,PT_Transjakarta,in,NaN,0,1,0,https://x.com/idlvsaygty/status/18632301591361...,1.540000e+18,idlvsaygty,12/1/2024 14:34,NaN
1,1.820000e+18,Sun Aug 11 07:43:40 +0000 2024,0,Gw tiap naik busway liat org make keyring truz...,1.820000e+18,NaN,NaN,in,𝖧𝗈𝗆𝗈𝗉𝗁𝗈𝖻𝗂𝖼 𝖽𝗇𝗂,0,0,0,https://x.com/cheershby/status/182253936505219...,1.410000e+18,cheershby,8/11/2024 7:43,NaN
2,1.840000e+18,Fri Sep 20 02:27:01 +0000 2024,0,Ampe kantor jam brp ini gue yaAllah ngestuck. ...,1.840000e+18,https://pbs.twimg.com/media/GX4odu4aQAAoz_1.jpg,NaN,in,Jakarta,0,0,0,https://x.com/joshonlee/status/183695519124726...,1.238640e+08,joshonlee,9/20/2024 2:27,NaN
3,1.870000e+18,Mon Dec 30 17:30:34 +0000 2024,0,⠀⠀⠀ &amp;. Anyway busway saya izin menyelam be...,1.870000e+18,NaN,NaN,in,1996. SFW. BIL (ENG/ID),0,0,0,https://x.com/InFortnight/status/1873783751718...,8.750000e+17,InFortnight,12/30/2024 17:30,NaN
4,1.820000e+18,Sun Aug 11 02:31:28 +0000 2024,0,Pdhl klen bisa menyulap tj mnjadi tayo bang bu...,1.820000e+18,NaN,NaN,in,mainly day6 riize txt,0,0,0,https://x.com/qohpisusu/status/182246079920356...,7.200000e+17,qohpisusu,8/11/2024 2:31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1.820000e+18,Mon Aug 05 02:47:47 +0000 2024,0,Hari hari depan halte busway https://t.co/iShF...,1.820000e+18,https://pbs.twimg.com/media/GUL4oKSWwAAR39O.jpg,NaN,in,"Swift Current, Saskatchewan",0,1,0,https://x.com/fyzlnrzl/status/1820290578363654199,2.646772e+08,fyzlnrzl,8/5/2024 2:47,NaN
1995,1.810000e+18,Mon Jul 01 02:19:21 +0000 2024,1,Pagi-pagi di busway otw kantor topup di @raide...,1.810000e+18,https://pbs.twimg.com/media/GRXid38a0AEzSyq.jpg,NaN,in,NaN,1,0,1,https://x.com/oceiann/status/1807599847677239461,1.310000e+18,oceiann,7/1/2024 2:19,NaN
1996,1.850000e+18,Mon Nov 04 11:32:27 +0000 2024,0,BENTAR HAO GUE MASIH DI BUSWAY,1.850000e+18,NaN,NaN,in,한빈.하오.규빈,0,0,0,https://x.com/bumblebeeen/status/1853399910223...,2.602640e+09,bumblebeeen,11/4/2024 11:32,NaN
1997,1.840000e+18,Mon Sep 16 14:54:58 +0000 2024,0,TJ ASTAGFIRULLAH SEMEIN GW AJA LAH SI IAN KASE...,1.840000e+18,https://pbs.twimg.com/media/GXmxv2Ca8AAxId4.png,NaN,in,Sinful Circus,0,0,0,https://x.com/nocturnal_clown/status/183569386...,4.160668e+08,nocturnal_clown,9/16/2024 14:54,NaN
1998,1.830000e+18,Tue Aug 20 22:35:02 +0000 2024,0,eemang paling enak tuh nyelak di antrian tj,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/ndaradasihi/status/1826025174787...,1.670000e+18,ndaradasihi,8/20/2024 22:35,NaN

In [ ]:
# SHOWS TWEETS THAT IS NOT IN INDONESIAN LANGUAGE

import pandas as pd

# Load the dataset
df_show_lang = df

# Define the regular expression pattern for the words to exclude
pattern = "(in)"

# Reassign df to only include tweets that do NOT contain any of the specified words
df_show_lang = df_show_lang[~df_show_lang['lang'].str.contains(pattern, case=False, na=False)]

# Now df_show_lang no longer includes the rows with the excluded words; view it in Data Wrangler/Data Viewer
df_show_lang

C:\Users\arsya\AppData\Local\Temp\ipykernel_6708\311252792.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_show_lang = df_show_lang[~df_show_lang['lang'].str.contains(pattern, case=False, na=False)]

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
17,1.830000e+18,Sun Sep 08 21:49:15 +0000 2024,1,tj easily lol,1.830000e+18,NaN,NaN,ht,NaN,0,1,0,https://x.com/Edudley_3/status/183289902354129...,4.580064e+08,Edudley_3,9/8/2024 21:49,NaN
434,1.830000e+18,Mon Aug 26 15:48:13 +0000 2024,0,Sayang bay 5 pa akung out ugma sa duty naa rab...,1.830000e+18,NaN,NaN,tl,Cdo // Butuan,0,0,0,https://x.com/Zacaralyl/status/182809712324367...,1.470000e+18,Zacaralyl,8/26/2024 15:48,NaN
486,1.820000e+18,Mon Aug 05 19:45:19 +0000 2024,0,hayp ka tj hahahzhaha,1.820000e+18,NaN,NaN,tl,NaN,0,0,0,https://x.com/ustxeya/status/1820546648860463558,1.670000e+18,ustxeya,8/5/2024 19:45,NaN
679,1.810000e+18,Sat Jul 13 09:52:18 +0000 2024,0,cek DM @PT_Transjakarta,1.810000e+18,NaN,NaN,tr,NaN,0,0,0,https://x.com/gontagantidulu/status/1812062490...,1.380000e+18,gontagantidulu,7/13/2024 9:52,NaN
740,1.820000e+18,Fri Aug 02 19:56:59 +0000 2024,0,TJ naman pakitang gilas masyado,1.820000e+18,NaN,NaN,tl,she/her,0,1,0,https://x.com/wayoftheace__/status/18194624191...,1.240000e+18,wayoftheace__,8/2/2024 19:56,NaN
814,1.830000e+18,Mon Aug 19 23:44:53 +0000 2024,0,anj live tracking tj ilang lg kah?!?! @PT_Tran...,1.830000e+18,NaN,NaN,tl,NaN,0,2,0,https://x.com/MuhammadAuliaR6/status/182568036...,1.027963e+09,MuhammadAuliaR6,8/19/2024 23:44,NaN
838,1.860000e+18,Fri Nov 29 09:09:48 +0000 2024,0,@ABSCBNNews Hayaan nalang yan wala namang aami...,1.860000e+18,NaN,ABSCBNNews,tl,Hong Kong/ Iloilo Philippines,0,0,0,https://x.com/Medjing2/status/1862423706322313681,1.610000e+18,Medjing2,11/29/2024 9:09,NaN
941,1.820000e+18,Sun Aug 04 22:27:39 +0000 2024,1,Ayia TJ #BBNaija,1.820000e+18,NaN,NaN,ht,"Abuja, Nigeria",0,0,0,https://x.com/koka_ba2/status/1820225113247056109,1.270000e+18,koka_ba2,8/4/2024 22:27,NaN
1041,1.820000e+18,Mon Aug 05 20:18:56 +0000 2024,0,bigay mo na lahat kay Tj yan Micah,1.820000e+18,NaN,NaN,tl,NaN,0,0,0,https://x.com/clepoiii/status/1820555109182656524,3.868646e+09,clepoiii,8/5/2024 20:18,NaN
1156,1.820000e+18,Sun Aug 04 20:53:11 +0000 2024,0,Tj is blaming Ben,1.820000e+18,NaN,NaN,nl,"Edmonton, Alberta",0,0,0,https://x.com/Nezr1/status/1820201338304929958,8.093010e+07,Nezr1,8/4/2024 20:53,NaN
1200,1.830000e+18,Sat Sep 14 10:38:03 +0000 2024,1,bagay kay Tj ung jersey,1.830000e+18,NaN,NaN,tl,"Dasmariñas, Cavite",0,0,0,https://x.com/ZhuPaul90/status/183490443588322...,1.080000e+18,ZhuPaul90,9/14/2024 10:38,NaN
1205,1.820000e+18,Fri Aug 02 14:37:06 +0000 2024,0,HAHAHAHAHAHAHAHAHAHHA TJ MAGSALITA KA,1.820000e+18,NaN,NaN,tl,"TOP,엠제이, 진진, 라키, 원우 💛💜💙",0,0,0,https://x.com/TabiEmzeeyWifeu/status/181938192...,1.050000e+18,TabiEmzeeyWifeu,8/2/2024 14:37,NaN
1259,1.850000e+18,Mon Oct 28 11:53:04 +0000 2024,4,Labing tatlo ang sugatan nang banggain ng isan...,1.850000e+18,https://pbs.twimg.com/media/Ga-a-U1W4AAcPIt.jpg,NaN,tl,Philippines,1,0,2,https://x.com/TVPatrol/status/1850868380883992838,1.544268e+08,TVPatrol,10/28/2024 11:53,NaN
1444,1.830000e+18,Fri Aug 30 17:18:53 +0000 2024,0,Yeaaaaaaaaaa TJ!!!,1.830000e+18,NaN,NaN,sv,"Indianapolis, IN",0,0,0,https://x.com/vmirelez58/status/18295694915269...,2.151218e+09,vmirelez58,8/30/2024 17:18,NaN
1554,1.830000e+18,Mon Sep 02 13:04:51 +0000 2024,0,BWISIT UTAS KAY TJ HAHAHAHHAHA,1.830000e+18,NaN,NaN,tl,NaN,0,0,0,https://x.com/Klooooowiiiiii/status/1830592724...,1.590000e+18,Klooooowiiiiii,9/2/2024 13:04,NaN
1812,1.870000e+18,Mon Dec 30 04:46:51 +0000 2024,0,@jarvees007 Hahahahah masa mau party naik busway,1.870000e+18,NaN,jarvees007,tl,"Jakarta Selatan, DKI Jakarta",0,1,0,https://x.com/piwpeewpiw/status/18735915568775...,1.560000e+18,piwpeewpiw,12/30/2024 4:46,NaN
1823,1.820000e+18,Sun Aug 04 23:01:08 +0000 2024,0,Ayia TJ #BBNaija,1.820000e+18,NaN,NaN,ht,"Abuja, Nigeria",0,0,0,https://x.com/koka_ba2/status/1820233539662582202,1.270000e+18,koka_ba2,8/4/2024 23:01,NaN
1904,1.820000e+18,Fri Aug 02 19:04:07 +0000 2024,2,kita niyo yang dilim na 'yan? Ganyan kadilim b...,1.820000e+18,NaN,NaN,tl,142208,0,0,0,https://x.com/yukicoded/status/181944911724202...,1.670000e+18,yukicoded,8/2/2024 19:04,NaN

In [ ]:
# Filter tweets that have the 'lang' column equal to 'in'
df = df[df['lang'] == 'in']

# View the filtered DataFrame
df

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
0,1.860000e+18,Sun Dec 01 14:34:21 +0000 2024,2,@PT_Transjakarta jadi buat besok kalau naik dr...,1.860000e+18,NaN,PT_Transjakarta,in,NaN,0,1,0,https://x.com/idlvsaygty/status/18632301591361...,1.540000e+18,idlvsaygty,12/1/2024 14:34,NaN
1,1.820000e+18,Sun Aug 11 07:43:40 +0000 2024,0,Gw tiap naik busway liat org make keyring truz...,1.820000e+18,NaN,NaN,in,𝖧𝗈𝗆𝗈𝗉𝗁𝗈𝖻𝗂𝖼 𝖽𝗇𝗂,0,0,0,https://x.com/cheershby/status/182253936505219...,1.410000e+18,cheershby,8/11/2024 7:43,NaN
2,1.840000e+18,Fri Sep 20 02:27:01 +0000 2024,0,Ampe kantor jam brp ini gue yaAllah ngestuck. ...,1.840000e+18,https://pbs.twimg.com/media/GX4odu4aQAAoz_1.jpg,NaN,in,Jakarta,0,0,0,https://x.com/joshonlee/status/183695519124726...,1.238640e+08,joshonlee,9/20/2024 2:27,NaN
3,1.870000e+18,Mon Dec 30 17:30:34 +0000 2024,0,⠀⠀⠀ &amp;. Anyway busway saya izin menyelam be...,1.870000e+18,NaN,NaN,in,1996. SFW. BIL (ENG/ID),0,0,0,https://x.com/InFortnight/status/1873783751718...,8.750000e+17,InFortnight,12/30/2024 17:30,NaN
4,1.820000e+18,Sun Aug 11 02:31:28 +0000 2024,0,Pdhl klen bisa menyulap tj mnjadi tayo bang bu...,1.820000e+18,NaN,NaN,in,mainly day6 riize txt,0,0,0,https://x.com/qohpisusu/status/182246079920356...,7.200000e+17,qohpisusu,8/11/2024 2:31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1.820000e+18,Mon Aug 05 02:47:47 +0000 2024,0,Hari hari depan halte busway https://t.co/iShF...,1.820000e+18,https://pbs.twimg.com/media/GUL4oKSWwAAR39O.jpg,NaN,in,"Swift Current, Saskatchewan",0,1,0,https://x.com/fyzlnrzl/status/1820290578363654199,2.646772e+08,fyzlnrzl,8/5/2024 2:47,NaN
1995,1.810000e+18,Mon Jul 01 02:19:21 +0000 2024,1,Pagi-pagi di busway otw kantor topup di @raide...,1.810000e+18,https://pbs.twimg.com/media/GRXid38a0AEzSyq.jpg,NaN,in,NaN,1,0,1,https://x.com/oceiann/status/1807599847677239461,1.310000e+18,oceiann,7/1/2024 2:19,NaN
1996,1.850000e+18,Mon Nov 04 11:32:27 +0000 2024,0,BENTAR HAO GUE MASIH DI BUSWAY,1.850000e+18,NaN,NaN,in,한빈.하오.규빈,0,0,0,https://x.com/bumblebeeen/status/1853399910223...,2.602640e+09,bumblebeeen,11/4/2024 11:32,NaN
1997,1.840000e+18,Mon Sep 16 14:54:58 +0000 2024,0,TJ ASTAGFIRULLAH SEMEIN GW AJA LAH SI IAN KASE...,1.840000e+18,https://pbs.twimg.com/media/GXmxv2Ca8AAxId4.png,NaN,in,Sinful Circus,0,0,0,https://x.com/nocturnal_clown/status/183569386...,4.160668e+08,nocturnal_clown,9/16/2024 14:54,NaN
1998,1.830000e+18,Tue Aug 20 22:35:02 +0000 2024,0,eemang paling enak tuh nyelak di antrian tj,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/ndaradasihi/status/1826025174787...,1.670000e+18,ndaradasihi,8/20/2024 22:35,NaN

In [ ]:
# Remove tweets that contain "#INFOTRANSJAKARTA" (case insensitive)
df = df[~df['full_text'].str.contains("#INFOTRANSJAKARTA", case=False, na=False)]

# View the updated DataFrame
df

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
0,1.860000e+18,Sun Dec 01 14:34:21 +0000 2024,2,@PT_Transjakarta jadi buat besok kalau naik dr...,1.860000e+18,NaN,PT_Transjakarta,in,NaN,0,1,0,https://x.com/idlvsaygty/status/18632301591361...,1.540000e+18,idlvsaygty,12/1/2024 14:34,NaN
1,1.820000e+18,Sun Aug 11 07:43:40 +0000 2024,0,Gw tiap naik busway liat org make keyring truz...,1.820000e+18,NaN,NaN,in,𝖧𝗈𝗆𝗈𝗉𝗁𝗈𝖻𝗂𝖼 𝖽𝗇𝗂,0,0,0,https://x.com/cheershby/status/182253936505219...,1.410000e+18,cheershby,8/11/2024 7:43,NaN
2,1.840000e+18,Fri Sep 20 02:27:01 +0000 2024,0,Ampe kantor jam brp ini gue yaAllah ngestuck. ...,1.840000e+18,https://pbs.twimg.com/media/GX4odu4aQAAoz_1.jpg,NaN,in,Jakarta,0,0,0,https://x.com/joshonlee/status/183695519124726...,1.238640e+08,joshonlee,9/20/2024 2:27,NaN
3,1.870000e+18,Mon Dec 30 17:30:34 +0000 2024,0,⠀⠀⠀ &amp;. Anyway busway saya izin menyelam be...,1.870000e+18,NaN,NaN,in,1996. SFW. BIL (ENG/ID),0,0,0,https://x.com/InFortnight/status/1873783751718...,8.750000e+17,InFortnight,12/30/2024 17:30,NaN
4,1.820000e+18,Sun Aug 11 02:31:28 +0000 2024,0,Pdhl klen bisa menyulap tj mnjadi tayo bang bu...,1.820000e+18,NaN,NaN,in,mainly day6 riize txt,0,0,0,https://x.com/qohpisusu/status/182246079920356...,7.200000e+17,qohpisusu,8/11/2024 2:31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1.820000e+18,Mon Aug 05 02:47:47 +0000 2024,0,Hari hari depan halte busway https://t.co/iShF...,1.820000e+18,https://pbs.twimg.com/media/GUL4oKSWwAAR39O.jpg,NaN,in,"Swift Current, Saskatchewan",0,1,0,https://x.com/fyzlnrzl/status/1820290578363654199,2.646772e+08,fyzlnrzl,8/5/2024 2:47,NaN
1995,1.810000e+18,Mon Jul 01 02:19:21 +0000 2024,1,Pagi-pagi di busway otw kantor topup di @raide...,1.810000e+18,https://pbs.twimg.com/media/GRXid38a0AEzSyq.jpg,NaN,in,NaN,1,0,1,https://x.com/oceiann/status/1807599847677239461,1.310000e+18,oceiann,7/1/2024 2:19,NaN
1996,1.850000e+18,Mon Nov 04 11:32:27 +0000 2024,0,BENTAR HAO GUE MASIH DI BUSWAY,1.850000e+18,NaN,NaN,in,한빈.하오.규빈,0,0,0,https://x.com/bumblebeeen/status/1853399910223...,2.602640e+09,bumblebeeen,11/4/2024 11:32,NaN
1997,1.840000e+18,Mon Sep 16 14:54:58 +0000 2024,0,TJ ASTAGFIRULLAH SEMEIN GW AJA LAH SI IAN KASE...,1.840000e+18,https://pbs.twimg.com/media/GXmxv2Ca8AAxId4.png,NaN,in,Sinful Circus,0,0,0,https://x.com/nocturnal_clown/status/183569386...,4.160668e+08,nocturnal_clown,9/16/2024 14:54,NaN
1998,1.830000e+18,Tue Aug 20 22:35:02 +0000 2024,0,eemang paling enak tuh nyelak di antrian tj,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/ndaradasihi/status/1826025174787...,1.670000e+18,ndaradasihi,8/20/2024 22:35,NaN

In [ ]:
# Remove duplicate tweets based on the "full_text" column, keeping the first occurrence
df = df.drop_duplicates(subset='full_text', keep='first')

# View the updated DataFrame
df

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
0,1.860000e+18,Sun Dec 01 14:34:21 +0000 2024,2,@PT_Transjakarta jadi buat besok kalau naik dr...,1.860000e+18,NaN,PT_Transjakarta,in,NaN,0,1,0,https://x.com/idlvsaygty/status/18632301591361...,1.540000e+18,idlvsaygty,12/1/2024 14:34,NaN
1,1.820000e+18,Sun Aug 11 07:43:40 +0000 2024,0,Gw tiap naik busway liat org make keyring truz...,1.820000e+18,NaN,NaN,in,𝖧𝗈𝗆𝗈𝗉𝗁𝗈𝖻𝗂𝖼 𝖽𝗇𝗂,0,0,0,https://x.com/cheershby/status/182253936505219...,1.410000e+18,cheershby,8/11/2024 7:43,NaN
2,1.840000e+18,Fri Sep 20 02:27:01 +0000 2024,0,Ampe kantor jam brp ini gue yaAllah ngestuck. ...,1.840000e+18,https://pbs.twimg.com/media/GX4odu4aQAAoz_1.jpg,NaN,in,Jakarta,0,0,0,https://x.com/joshonlee/status/183695519124726...,1.238640e+08,joshonlee,9/20/2024 2:27,NaN
3,1.870000e+18,Mon Dec 30 17:30:34 +0000 2024,0,⠀⠀⠀ &amp;. Anyway busway saya izin menyelam be...,1.870000e+18,NaN,NaN,in,1996. SFW. BIL (ENG/ID),0,0,0,https://x.com/InFortnight/status/1873783751718...,8.750000e+17,InFortnight,12/30/2024 17:30,NaN
4,1.820000e+18,Sun Aug 11 02:31:28 +0000 2024,0,Pdhl klen bisa menyulap tj mnjadi tayo bang bu...,1.820000e+18,NaN,NaN,in,mainly day6 riize txt,0,0,0,https://x.com/qohpisusu/status/182246079920356...,7.200000e+17,qohpisusu,8/11/2024 2:31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1.820000e+18,Mon Aug 05 02:47:47 +0000 2024,0,Hari hari depan halte busway https://t.co/iShF...,1.820000e+18,https://pbs.twimg.com/media/GUL4oKSWwAAR39O.jpg,NaN,in,"Swift Current, Saskatchewan",0,1,0,https://x.com/fyzlnrzl/status/1820290578363654199,2.646772e+08,fyzlnrzl,8/5/2024 2:47,NaN
1995,1.810000e+18,Mon Jul 01 02:19:21 +0000 2024,1,Pagi-pagi di busway otw kantor topup di @raide...,1.810000e+18,https://pbs.twimg.com/media/GRXid38a0AEzSyq.jpg,NaN,in,NaN,1,0,1,https://x.com/oceiann/status/1807599847677239461,1.310000e+18,oceiann,7/1/2024 2:19,NaN
1996,1.850000e+18,Mon Nov 04 11:32:27 +0000 2024,0,BENTAR HAO GUE MASIH DI BUSWAY,1.850000e+18,NaN,NaN,in,한빈.하오.규빈,0,0,0,https://x.com/bumblebeeen/status/1853399910223...,2.602640e+09,bumblebeeen,11/4/2024 11:32,NaN
1997,1.840000e+18,Mon Sep 16 14:54:58 +0000 2024,0,TJ ASTAGFIRULLAH SEMEIN GW AJA LAH SI IAN KASE...,1.840000e+18,https://pbs.twimg.com/media/GXmxv2Ca8AAxId4.png,NaN,in,Sinful Circus,0,0,0,https://x.com/nocturnal_clown/status/183569386...,4.160668e+08,nocturnal_clown,9/16/2024 14:54,NaN
1998,1.830000e+18,Tue Aug 20 22:35:02 +0000 2024,0,eemang paling enak tuh nyelak di antrian tj,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/ndaradasihi/status/1826025174787...,1.670000e+18,ndaradasihi,8/20/2024 22:35,NaN

In [ ]:
# Remove tweets where the 'username' column equals "26Ceicei"
df = df[df['username'] != "26Ceicei"]

# View the updated DataFrame
df

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
0,1.860000e+18,Sun Dec 01 14:34:21 +0000 2024,2,@PT_Transjakarta jadi buat besok kalau naik dr...,1.860000e+18,NaN,PT_Transjakarta,in,NaN,0,1,0,https://x.com/idlvsaygty/status/18632301591361...,1.540000e+18,idlvsaygty,12/1/2024 14:34,NaN
1,1.820000e+18,Sun Aug 11 07:43:40 +0000 2024,0,Gw tiap naik busway liat org make keyring truz...,1.820000e+18,NaN,NaN,in,𝖧𝗈𝗆𝗈𝗉𝗁𝗈𝖻𝗂𝖼 𝖽𝗇𝗂,0,0,0,https://x.com/cheershby/status/182253936505219...,1.410000e+18,cheershby,8/11/2024 7:43,NaN
2,1.840000e+18,Fri Sep 20 02:27:01 +0000 2024,0,Ampe kantor jam brp ini gue yaAllah ngestuck. ...,1.840000e+18,https://pbs.twimg.com/media/GX4odu4aQAAoz_1.jpg,NaN,in,Jakarta,0,0,0,https://x.com/joshonlee/status/183695519124726...,1.238640e+08,joshonlee,9/20/2024 2:27,NaN
3,1.870000e+18,Mon Dec 30 17:30:34 +0000 2024,0,⠀⠀⠀ &amp;. Anyway busway saya izin menyelam be...,1.870000e+18,NaN,NaN,in,1996. SFW. BIL (ENG/ID),0,0,0,https://x.com/InFortnight/status/1873783751718...,8.750000e+17,InFortnight,12/30/2024 17:30,NaN
4,1.820000e+18,Sun Aug 11 02:31:28 +0000 2024,0,Pdhl klen bisa menyulap tj mnjadi tayo bang bu...,1.820000e+18,NaN,NaN,in,mainly day6 riize txt,0,0,0,https://x.com/qohpisusu/status/182246079920356...,7.200000e+17,qohpisusu,8/11/2024 2:31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1.820000e+18,Mon Aug 05 02:47:47 +0000 2024,0,Hari hari depan halte busway https://t.co/iShF...,1.820000e+18,https://pbs.twimg.com/media/GUL4oKSWwAAR39O.jpg,NaN,in,"Swift Current, Saskatchewan",0,1,0,https://x.com/fyzlnrzl/status/1820290578363654199,2.646772e+08,fyzlnrzl,8/5/2024 2:47,NaN
1995,1.810000e+18,Mon Jul 01 02:19:21 +0000 2024,1,Pagi-pagi di busway otw kantor topup di @raide...,1.810000e+18,https://pbs.twimg.com/media/GRXid38a0AEzSyq.jpg,NaN,in,NaN,1,0,1,https://x.com/oceiann/status/1807599847677239461,1.310000e+18,oceiann,7/1/2024 2:19,NaN
1996,1.850000e+18,Mon Nov 04 11:32:27 +0000 2024,0,BENTAR HAO GUE MASIH DI BUSWAY,1.850000e+18,NaN,NaN,in,한빈.하오.규빈,0,0,0,https://x.com/bumblebeeen/status/1853399910223...,2.602640e+09,bumblebeeen,11/4/2024 11:32,NaN
1997,1.840000e+18,Mon Sep 16 14:54:58 +0000 2024,0,TJ ASTAGFIRULLAH SEMEIN GW AJA LAH SI IAN KASE...,1.840000e+18,https://pbs.twimg.com/media/GXmxv2Ca8AAxId4.png,NaN,in,Sinful Circus,0,0,0,https://x.com/nocturnal_clown/status/183569386...,4.160668e+08,nocturnal_clown,9/16/2024 14:54,NaN
1998,1.830000e+18,Tue Aug 20 22:35:02 +0000 2024,0,eemang paling enak tuh nyelak di antrian tj,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/ndaradasihi/status/1826025174787...,1.670000e+18,ndaradasihi,8/20/2024 22:35,NaN

In [ ]:
# Filter tweets that contain "min" or "kak" (case insensitive) AND a question mark "?"
filtered_tweets = df[
    df['full_text'].str.contains(r"(min|kak|admin.*info|info.*admin|min.*info|info.*min)", case=False, na=False) &
    df['full_text'].str.contains(r"\?", na=False)
]

# View the resulting DataFrame
filtered_tweets

C:\Users\arsya\AppData\Local\Temp\ipykernel_6708\3395848046.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df['full_text'].str.contains(r"(min|kak|admin.*info|info.*admin|min.*info|info.*min)", case=False, na=False) &

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
13,1.850000e+18,Wed Oct 23 23:29:37 +0000 2024,0,Posisi S11 dmn min @PT_Transjakarta ? Saya sdh...,1.850000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/AgnesSitum1868/status/1849231735...,1.820000e+18,AgnesSitum1868,10/23/2024 23:29,NaN
14,1.850000e+18,Sat Oct 19 14:18:15 +0000 2024,0,min @PT_Transjakarta besok bus D21 ada pengali...,1.850000e+18,NaN,NaN,in,soyi,0,1,0,https://x.com/aunotrin/status/1847643426709524534,1.820000e+18,aunotrin,10/19/2024 14:18,NaN
19,1.820000e+18,Sat Aug 17 10:24:57 +0000 2024,0,Admin @PT_Transjakarta mau nanyaa kalau dari H...,1.820000e+18,NaN,NaN,in,#찬열,0,1,0,https://x.com/SunsetForCY/status/1824754279389...,1.260000e+18,SunsetForCY,8/17/2024 10:24,NaN
41,1.870000e+18,Wed Dec 11 08:20:49 +0000 2024,0,punten min @PT_Transjakarta kalo mau ke alamat...,1.870000e+18,https://pbs.twimg.com/media/GegQW8VbgAEN0Ep.jpg,NaN,in,hawkins,0,1,0,https://x.com/astrownoh/status/186676003366256...,1.140000e+18,astrownoh,12/11/2024 8:20,NaN
50,1.810000e+18,Sat Jul 06 08:04:49 +0000 2024,0,Min kalo mau ke PRJ naik tj dari Tangerang gim...,1.810000e+18,NaN,NaN,in,Bikini Bottom,0,1,0,https://x.com/bananacoklad/status/180949872311...,2.327044e+09,bananacoklad,7/6/2024 8:04,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1943,1.820000e+18,Tue Jul 30 03:39:13 +0000 2024,0,@PT_Transjakarta Hallo admin. Udh mau seminggu...,1.820000e+18,NaN,PT_Transjakarta,in,NaN,0,0,0,https://x.com/johnnysuhcrush/status/1818129191...,1.080000e+18,johnnysuhcrush,7/30/2024 3:39,NaN
1960,1.810000e+18,Sat Jul 20 12:56:37 +0000 2024,0,Halo kak mau tanya kalau dari arah halte Damai...,1.810000e+18,NaN,NaN,in,-,0,1,0,https://x.com/dnfkslan/status/1814645589801640227,1.080000e+18,dnfkslan,7/20/2024 12:56,NaN
1965,1.840000e+18,Mon Oct 07 07:17:03 +0000 2024,0,Min info jalur tercepat dari halte palem semi ...,1.840000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/Schwein5teiger/status/1843188776...,1.210000e+18,Schwein5teiger,10/7/2024 7:17,NaN
1982,1.820000e+18,Fri Jul 26 02:45:16 +0000 2024,0,Halo min @PT_Transjakarta mohon infonya antara...,1.820000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/kaliputt/status/1816666065809879078,7.716562e+07,kaliputt,7/26/2024 2:45,NaN
1985,1.840000e+18,Wed Oct 02 06:01:35 +0000 2024,11,@irhamsyarif @PT_Transjakarta Udah ganti nama ...,1.840000e+18,NaN,irhamsyarif,in,British Indian Ocean Territory,0,1,0,https://x.com/jeffreysantio/status/18413578441...,7.949176e+07,jeffreysantio,10/2/2024 6:01,NaN

In [ ]:
# Define the pattern to drop tweets (those asking questions in a style you want to exclude)
drop_pattern = r"(min|kak|admin.*info|info.*admin|min.*info|info.*min)"
mask_drop = df['full_text'].str.contains(drop_pattern, case=False, na=False) & \
            df['full_text'].str.contains(r"\?", na=False)

# Define a list of tweets to keep even if they match the drop pattern
whitelist = [
    "iya anjenggg tolong lah itu gua JALAN KAKI di pinggiran pancoran sama kuningan pas abis ujan aja rasanya mau kepleset mulu jalanan super licin! dahlah naik busway juga bobrok ac suka mati jadi sebenernya pajak naik tuh BUAT APA nying kalau hasil FASILITASNYA GA ADA?!",
    "minnn @PT_Transjakarta 7B arah blok m kok lama yaaa? dari halte duren tiga ga muncul muncul",
    "Haloo min @PT_Transjakarta sore tadi saya top up saldo flazz di salah satu mesin halte Transjakarta tapi di tulisan mesinnya gagal sedangkan saldo bank saya kesedot sesuai minimal top up saya. Itu gimana ya min? Apakah ada refund terkait hal ini dan bagaimana mekanismenya",
    "min tj 6w kok selalu lama sih boleh banget ditambah akomodasi nya. btw hari ini beroperasi ga? udh nunggu lumayan lama nggak lewat2 @PT_Transjakarta",
    "Min klo isi kartunya gagal pas bayar pake QR itu nnt sistem refund nya gmn ya?? Soalnya udh 3hari blm ke refund jg @PT_Transjakarta",
    "Halo admin @PT_Transjakarta. Pulang kerja aku naik JAK39 ini serius beberapa armada kalian pasang iklan full body aplikasi pinjol?",
    "Busway rute Blok M - Meruya ini emang waktu tunggunya bisa sekitar 45 menit di CSW ya? Masalahnya dimana deh armadanya kurang apa timingnya gak pas apa gimana? (Dari saya yang berdiri di CSW udah 45 menit menyaksikan 2 bus arah Pesanggrahan dan Rempoa lewat) @PT_Transjakarta",
    "Jak 89 ke Tg. Priok bus stop nya dimana sih sebenernya??? Saya nunggu di samping terminal diblg suruh di depan udah berhenti di depan pun jg disuruh ke samping lg di oper2 melulu. Kejelasannya dong tolong... aneh banget miskomunikasi gini bikin bingung. @PT_Transjakarta",
    "Sumpah TJ koridor 1 tiap di terminal Blok M itu ngapain sih bisa diem selama itu?? Nungguin apa anjg?? Udah berapa kali aja gua telat gara-gara itu bus berentet panjang di jalur 1 kontol-kontol gua berangkat mau pagi/siang kalo TJ nya yang lelet gua bakalan tetep telat.",
    "Min kenapa aplikasi tije pas di klik kode busnya malah gak ada info tujuan akhirnya ?? Itu hampir semuanya loh @PT_Transjakarta",
    "kak @PT_Transjakarta tadi saya naik tj tapi mesin tap out nya loading lama banget dan pas mau tap out ga bisa bisa jadi kata abang nya turun aja. Kalo gitu kartu saya ke blokir ga kak?",
    "min tolong kekkkkk ada himbauan dilarang ngerumpi ngobrol di transjakarta. berisikkkk bgt teriak2 ketawa2 dikira mobil pribadi kahhhh??apalagi rute pulogadung-galunggung pas halte unj itu berisik bgt222 org2 yg naik tj nya @PT_Transjakarta",
    "Dmei tuhan busway ga dateng2 ini gw jalan kaki aja kah 4km??",
    "Lagi ada yg kemalingan hp di Halte karet lagi! @PT_Transjakarta kalau kaya gini mau ngelapor ke siapa masa iya hampir tiap minggu hp ilang ga bisa ketangkep? Siklusnya sama pas ditanya ke petugas wah itumah susah . Template. Yg hpnya ilang di copet di tj. Bisa share disini! https://t.co/XtLb9n2jq2",
    "dah 2 hari tracking TJ di Google Maps mati (lagi dan lagi) colokan server ente kecabut kali ya min? apa nuraninya yang udah kecabut jg ?cuma perkara tracking aja bisa mati hidup. app kalian yg baru itu jelek @PT_Transjakarta @txttransportasi @TfJakarta @TransKopaja"
]

# Create a mask for tweets that are in the whitelist
mask_keep = df['full_text'].isin(whitelist)

# Remove tweets that match the drop pattern but are not in the whitelist
df_filtered = df[~(mask_drop & ~mask_keep)]

# View the resulting DataFrame
df_filtered

df = df_filtered

C:\Users\arsya\AppData\Local\Temp\ipykernel_6708\3448906110.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask_drop = df['full_text'].str.contains(drop_pattern, case=False, na=False) & \

In [ ]:
df

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
0,1.860000e+18,Sun Dec 01 14:34:21 +0000 2024,2,@PT_Transjakarta jadi buat besok kalau naik dr...,1.860000e+18,NaN,PT_Transjakarta,in,NaN,0,1,0,https://x.com/idlvsaygty/status/18632301591361...,1.540000e+18,idlvsaygty,12/1/2024 14:34,NaN
1,1.820000e+18,Sun Aug 11 07:43:40 +0000 2024,0,Gw tiap naik busway liat org make keyring truz...,1.820000e+18,NaN,NaN,in,𝖧𝗈𝗆𝗈𝗉𝗁𝗈𝖻𝗂𝖼 𝖽𝗇𝗂,0,0,0,https://x.com/cheershby/status/182253936505219...,1.410000e+18,cheershby,8/11/2024 7:43,NaN
2,1.840000e+18,Fri Sep 20 02:27:01 +0000 2024,0,Ampe kantor jam brp ini gue yaAllah ngestuck. ...,1.840000e+18,https://pbs.twimg.com/media/GX4odu4aQAAoz_1.jpg,NaN,in,Jakarta,0,0,0,https://x.com/joshonlee/status/183695519124726...,1.238640e+08,joshonlee,9/20/2024 2:27,NaN
3,1.870000e+18,Mon Dec 30 17:30:34 +0000 2024,0,⠀⠀⠀ &amp;. Anyway busway saya izin menyelam be...,1.870000e+18,NaN,NaN,in,1996. SFW. BIL (ENG/ID),0,0,0,https://x.com/InFortnight/status/1873783751718...,8.750000e+17,InFortnight,12/30/2024 17:30,NaN
4,1.820000e+18,Sun Aug 11 02:31:28 +0000 2024,0,Pdhl klen bisa menyulap tj mnjadi tayo bang bu...,1.820000e+18,NaN,NaN,in,mainly day6 riize txt,0,0,0,https://x.com/qohpisusu/status/182246079920356...,7.200000e+17,qohpisusu,8/11/2024 2:31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1.820000e+18,Mon Aug 05 02:47:47 +0000 2024,0,Hari hari depan halte busway https://t.co/iShF...,1.820000e+18,https://pbs.twimg.com/media/GUL4oKSWwAAR39O.jpg,NaN,in,"Swift Current, Saskatchewan",0,1,0,https://x.com/fyzlnrzl/status/1820290578363654199,2.646772e+08,fyzlnrzl,8/5/2024 2:47,NaN
1995,1.810000e+18,Mon Jul 01 02:19:21 +0000 2024,1,Pagi-pagi di busway otw kantor topup di @raide...,1.810000e+18,https://pbs.twimg.com/media/GRXid38a0AEzSyq.jpg,NaN,in,NaN,1,0,1,https://x.com/oceiann/status/1807599847677239461,1.310000e+18,oceiann,7/1/2024 2:19,NaN
1996,1.850000e+18,Mon Nov 04 11:32:27 +0000 2024,0,BENTAR HAO GUE MASIH DI BUSWAY,1.850000e+18,NaN,NaN,in,한빈.하오.규빈,0,0,0,https://x.com/bumblebeeen/status/1853399910223...,2.602640e+09,bumblebeeen,11/4/2024 11:32,NaN
1997,1.840000e+18,Mon Sep 16 14:54:58 +0000 2024,0,TJ ASTAGFIRULLAH SEMEIN GW AJA LAH SI IAN KASE...,1.840000e+18,https://pbs.twimg.com/media/GXmxv2Ca8AAxId4.png,NaN,in,Sinful Circus,0,0,0,https://x.com/nocturnal_clown/status/183569386...,4.160668e+08,nocturnal_clown,9/16/2024 14:54,NaN
1998,1.830000e+18,Tue Aug 20 22:35:02 +0000 2024,0,eemang paling enak tuh nyelak di antrian tj,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/ndaradasihi/status/1826025174787...,1.670000e+18,ndaradasihi,8/20/2024 22:35,NaN

In [ ]:
# SHOWS TWEETS THAT IS NOT IN INDONESIAN LANGUAGE

# Load the dataset
df_show_TJ_WATT = df

# Define the regular expression pattern for the words to exclude
pattern = "TJ Watt"

# Reassign df to only include tweets that do NOT contain any of the specified words
df_show_TJ_WATT = df_show_TJ_WATT[df_show_TJ_WATT['full_text'].str.contains(pattern, case=False, na=False)]

# Now df_show_TJ_WATT no longer includes the rows with the excluded words; view it in Data Wrangler/Data Viewer
df_show_TJ_WATT

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
293,1.830000e+18,Sun Sep 08 18:44:41 +0000 2024,0,TJ WATTTTTTT,1.830000e+18,NaN,NaN,in,Jersey,0,0,0,https://x.com/_oosoom/status/1832852574535569408,3.732819e+07,_oosoom,9/8/2024 18:44,NaN
378,1.830000e+18,Sun Sep 08 18:44:34 +0000 2024,0,TJ Watt is phenomenal,1.830000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/futurenbagov/status/183285254549...,2.888878e+09,futurenbagov,9/8/2024 18:44,NaN
431,1.830000e+18,Sun Sep 08 17:10:58 +0000 2024,1,TJ WATTTTTT,1.830000e+18,NaN,NaN,in,"Chicago, IL",0,0,0,https://x.com/yourrrfavdani/status/18328289922...,1.580000e+18,yourrrfavdani,9/8/2024 17:10,NaN
936,1.830000e+18,Sun Sep 08 19:59:39 +0000 2024,0,TJ Watt. Wow.,1.830000e+18,NaN,NaN,in,The Bronx & The DMV,0,0,0,https://x.com/ImmanuelJames/status/18328714435...,1.849207e+07,ImmanuelJames,9/8/2024 19:59,NaN
975,1.830000e+18,Sun Sep 08 18:44:18 +0000 2024,0,TJ WATTTTT,1.830000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/LouieB1x/status/1832852478058180866,1.095956e+08,LouieB1x,9/8/2024 18:44,NaN
1015,1.830000e+18,Sun Sep 08 20:02:18 +0000 2024,0,TJ WATT IS HIM,1.830000e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/nysports_10/status/1832872108801...,1.480000e+18,nysports_10,9/8/2024 20:02,NaN
1254,1.830000e+18,Sun Sep 08 18:49:01 +0000 2024,0,TJ Watt is generational bro,1.830000e+18,NaN,NaN,in,Somewhere ‘round here,0,0,0,https://x.com/jay1_of1/status/1832853665864118482,2.932868e+09,jay1_of1,9/8/2024 18:49,NaN
1285,1.830000e+18,Sun Sep 08 18:59:07 +0000 2024,3,TJ Watt DPOY,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/mp2fye25/status/1832856208903909762,1.470000e+18,mp2fye25,9/8/2024 18:59,NaN
1405,1.830000e+18,Sun Sep 08 19:00:45 +0000 2024,1,TJ Watt masterclass,1.830000e+18,NaN,NaN,in,"Decatur, GA",0,0,0,https://x.com/DefaultReece/status/183285662096...,1.074938e+08,DefaultReece,9/8/2024 19:00,NaN
1546,1.830000e+18,Sun Sep 08 20:00:15 +0000 2024,1,TJ WATTT,1.830000e+18,NaN,NaN,in,Hillsborough NJ,0,1,0,https://x.com/P0ly95/status/1832871592059117692,1.774579e+08,P0ly95,9/8/2024 20:00,NaN
1828,1.830000e+18,Sun Sep 08 19:16:26 +0000 2024,0,TJ WATT terrorizing that RT,1.830000e+18,NaN,NaN,in,"Metro Atlanta, Ga",0,0,0,https://x.com/DeliMeeks/status/183286056545198...,3.009344e+07,DeliMeeks,9/8/2024 19:16,NaN

In [ ]:
# Remove tweets that contain "TJ Watt" (case insensitive)
df = df[~df['full_text'].str.contains("TJ Watt", case=False, na=False)]

# View the updated DataFrame
df

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
0,1.860000e+18,Sun Dec 01 14:34:21 +0000 2024,2,@PT_Transjakarta jadi buat besok kalau naik dr...,1.860000e+18,NaN,PT_Transjakarta,in,NaN,0,1,0,https://x.com/idlvsaygty/status/18632301591361...,1.540000e+18,idlvsaygty,12/1/2024 14:34,NaN
1,1.820000e+18,Sun Aug 11 07:43:40 +0000 2024,0,Gw tiap naik busway liat org make keyring truz...,1.820000e+18,NaN,NaN,in,𝖧𝗈𝗆𝗈𝗉𝗁𝗈𝖻𝗂𝖼 𝖽𝗇𝗂,0,0,0,https://x.com/cheershby/status/182253936505219...,1.410000e+18,cheershby,8/11/2024 7:43,NaN
2,1.840000e+18,Fri Sep 20 02:27:01 +0000 2024,0,Ampe kantor jam brp ini gue yaAllah ngestuck. ...,1.840000e+18,https://pbs.twimg.com/media/GX4odu4aQAAoz_1.jpg,NaN,in,Jakarta,0,0,0,https://x.com/joshonlee/status/183695519124726...,1.238640e+08,joshonlee,9/20/2024 2:27,NaN
3,1.870000e+18,Mon Dec 30 17:30:34 +0000 2024,0,⠀⠀⠀ &amp;. Anyway busway saya izin menyelam be...,1.870000e+18,NaN,NaN,in,1996. SFW. BIL (ENG/ID),0,0,0,https://x.com/InFortnight/status/1873783751718...,8.750000e+17,InFortnight,12/30/2024 17:30,NaN
4,1.820000e+18,Sun Aug 11 02:31:28 +0000 2024,0,Pdhl klen bisa menyulap tj mnjadi tayo bang bu...,1.820000e+18,NaN,NaN,in,mainly day6 riize txt,0,0,0,https://x.com/qohpisusu/status/182246079920356...,7.200000e+17,qohpisusu,8/11/2024 2:31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1.820000e+18,Mon Aug 05 02:47:47 +0000 2024,0,Hari hari depan halte busway https://t.co/iShF...,1.820000e+18,https://pbs.twimg.com/media/GUL4oKSWwAAR39O.jpg,NaN,in,"Swift Current, Saskatchewan",0,1,0,https://x.com/fyzlnrzl/status/1820290578363654199,2.646772e+08,fyzlnrzl,8/5/2024 2:47,NaN
1995,1.810000e+18,Mon Jul 01 02:19:21 +0000 2024,1,Pagi-pagi di busway otw kantor topup di @raide...,1.810000e+18,https://pbs.twimg.com/media/GRXid38a0AEzSyq.jpg,NaN,in,NaN,1,0,1,https://x.com/oceiann/status/1807599847677239461,1.310000e+18,oceiann,7/1/2024 2:19,NaN
1996,1.850000e+18,Mon Nov 04 11:32:27 +0000 2024,0,BENTAR HAO GUE MASIH DI BUSWAY,1.850000e+18,NaN,NaN,in,한빈.하오.규빈,0,0,0,https://x.com/bumblebeeen/status/1853399910223...,2.602640e+09,bumblebeeen,11/4/2024 11:32,NaN
1997,1.840000e+18,Mon Sep 16 14:54:58 +0000 2024,0,TJ ASTAGFIRULLAH SEMEIN GW AJA LAH SI IAN KASE...,1.840000e+18,https://pbs.twimg.com/media/GXmxv2Ca8AAxId4.png,NaN,in,Sinful Circus,0,0,0,https://x.com/nocturnal_clown/status/183569386...,4.160668e+08,nocturnal_clown,9/16/2024 14:54,NaN
1998,1.830000e+18,Tue Aug 20 22:35:02 +0000 2024,0,eemang paling enak tuh nyelak di antrian tj,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/ndaradasihi/status/1826025174787...,1.670000e+18,ndaradasihi,8/20/2024 22:35,NaN

In [ ]:
# Remove tweets that contain "TJ Watt" (case insensitive)
df = df[~df['full_text'].str.contains("TJ What", case=False, na=False)]

# View the updated DataFrame
df

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
0,1.860000e+18,Sun Dec 01 14:34:21 +0000 2024,2,@PT_Transjakarta jadi buat besok kalau naik dr...,1.860000e+18,NaN,PT_Transjakarta,in,NaN,0,1,0,https://x.com/idlvsaygty/status/18632301591361...,1.540000e+18,idlvsaygty,12/1/2024 14:34,NaN
1,1.820000e+18,Sun Aug 11 07:43:40 +0000 2024,0,Gw tiap naik busway liat org make keyring truz...,1.820000e+18,NaN,NaN,in,𝖧𝗈𝗆𝗈𝗉𝗁𝗈𝖻𝗂𝖼 𝖽𝗇𝗂,0,0,0,https://x.com/cheershby/status/182253936505219...,1.410000e+18,cheershby,8/11/2024 7:43,NaN
2,1.840000e+18,Fri Sep 20 02:27:01 +0000 2024,0,Ampe kantor jam brp ini gue yaAllah ngestuck. ...,1.840000e+18,https://pbs.twimg.com/media/GX4odu4aQAAoz_1.jpg,NaN,in,Jakarta,0,0,0,https://x.com/joshonlee/status/183695519124726...,1.238640e+08,joshonlee,9/20/2024 2:27,NaN
3,1.870000e+18,Mon Dec 30 17:30:34 +0000 2024,0,⠀⠀⠀ &amp;. Anyway busway saya izin menyelam be...,1.870000e+18,NaN,NaN,in,1996. SFW. BIL (ENG/ID),0,0,0,https://x.com/InFortnight/status/1873783751718...,8.750000e+17,InFortnight,12/30/2024 17:30,NaN
4,1.820000e+18,Sun Aug 11 02:31:28 +0000 2024,0,Pdhl klen bisa menyulap tj mnjadi tayo bang bu...,1.820000e+18,NaN,NaN,in,mainly day6 riize txt,0,0,0,https://x.com/qohpisusu/status/182246079920356...,7.200000e+17,qohpisusu,8/11/2024 2:31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1.820000e+18,Mon Aug 05 02:47:47 +0000 2024,0,Hari hari depan halte busway https://t.co/iShF...,1.820000e+18,https://pbs.twimg.com/media/GUL4oKSWwAAR39O.jpg,NaN,in,"Swift Current, Saskatchewan",0,1,0,https://x.com/fyzlnrzl/status/1820290578363654199,2.646772e+08,fyzlnrzl,8/5/2024 2:47,NaN
1995,1.810000e+18,Mon Jul 01 02:19:21 +0000 2024,1,Pagi-pagi di busway otw kantor topup di @raide...,1.810000e+18,https://pbs.twimg.com/media/GRXid38a0AEzSyq.jpg,NaN,in,NaN,1,0,1,https://x.com/oceiann/status/1807599847677239461,1.310000e+18,oceiann,7/1/2024 2:19,NaN
1996,1.850000e+18,Mon Nov 04 11:32:27 +0000 2024,0,BENTAR HAO GUE MASIH DI BUSWAY,1.850000e+18,NaN,NaN,in,한빈.하오.규빈,0,0,0,https://x.com/bumblebeeen/status/1853399910223...,2.602640e+09,bumblebeeen,11/4/2024 11:32,NaN
1997,1.840000e+18,Mon Sep 16 14:54:58 +0000 2024,0,TJ ASTAGFIRULLAH SEMEIN GW AJA LAH SI IAN KASE...,1.840000e+18,https://pbs.twimg.com/media/GXmxv2Ca8AAxId4.png,NaN,in,Sinful Circus,0,0,0,https://x.com/nocturnal_clown/status/183569386...,4.160668e+08,nocturnal_clown,9/16/2024 14:54,NaN
1998,1.830000e+18,Tue Aug 20 22:35:02 +0000 2024,0,eemang paling enak tuh nyelak di antrian tj,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/ndaradasihi/status/1826025174787...,1.670000e+18,ndaradasihi,8/20/2024 22:35,NaN

In [ ]:
# Remove tweets that contain "TJ Watt" (case insensitive)
df = df[~df['full_text'].str.contains("info rute", case=False, na=False)]

# View the updated DataFrame
df

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
0,1.860000e+18,Sun Dec 01 14:34:21 +0000 2024,2,@PT_Transjakarta jadi buat besok kalau naik dr...,1.860000e+18,NaN,PT_Transjakarta,in,NaN,0,1,0,https://x.com/idlvsaygty/status/18632301591361...,1.540000e+18,idlvsaygty,12/1/2024 14:34,NaN
1,1.820000e+18,Sun Aug 11 07:43:40 +0000 2024,0,Gw tiap naik busway liat org make keyring truz...,1.820000e+18,NaN,NaN,in,𝖧𝗈𝗆𝗈𝗉𝗁𝗈𝖻𝗂𝖼 𝖽𝗇𝗂,0,0,0,https://x.com/cheershby/status/182253936505219...,1.410000e+18,cheershby,8/11/2024 7:43,NaN
2,1.840000e+18,Fri Sep 20 02:27:01 +0000 2024,0,Ampe kantor jam brp ini gue yaAllah ngestuck. ...,1.840000e+18,https://pbs.twimg.com/media/GX4odu4aQAAoz_1.jpg,NaN,in,Jakarta,0,0,0,https://x.com/joshonlee/status/183695519124726...,1.238640e+08,joshonlee,9/20/2024 2:27,NaN
3,1.870000e+18,Mon Dec 30 17:30:34 +0000 2024,0,⠀⠀⠀ &amp;. Anyway busway saya izin menyelam be...,1.870000e+18,NaN,NaN,in,1996. SFW. BIL (ENG/ID),0,0,0,https://x.com/InFortnight/status/1873783751718...,8.750000e+17,InFortnight,12/30/2024 17:30,NaN
4,1.820000e+18,Sun Aug 11 02:31:28 +0000 2024,0,Pdhl klen bisa menyulap tj mnjadi tayo bang bu...,1.820000e+18,NaN,NaN,in,mainly day6 riize txt,0,0,0,https://x.com/qohpisusu/status/182246079920356...,7.200000e+17,qohpisusu,8/11/2024 2:31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1.820000e+18,Mon Aug 05 02:47:47 +0000 2024,0,Hari hari depan halte busway https://t.co/iShF...,1.820000e+18,https://pbs.twimg.com/media/GUL4oKSWwAAR39O.jpg,NaN,in,"Swift Current, Saskatchewan",0,1,0,https://x.com/fyzlnrzl/status/1820290578363654199,2.646772e+08,fyzlnrzl,8/5/2024 2:47,NaN
1995,1.810000e+18,Mon Jul 01 02:19:21 +0000 2024,1,Pagi-pagi di busway otw kantor topup di @raide...,1.810000e+18,https://pbs.twimg.com/media/GRXid38a0AEzSyq.jpg,NaN,in,NaN,1,0,1,https://x.com/oceiann/status/1807599847677239461,1.310000e+18,oceiann,7/1/2024 2:19,NaN
1996,1.850000e+18,Mon Nov 04 11:32:27 +0000 2024,0,BENTAR HAO GUE MASIH DI BUSWAY,1.850000e+18,NaN,NaN,in,한빈.하오.규빈,0,0,0,https://x.com/bumblebeeen/status/1853399910223...,2.602640e+09,bumblebeeen,11/4/2024 11:32,NaN
1997,1.840000e+18,Mon Sep 16 14:54:58 +0000 2024,0,TJ ASTAGFIRULLAH SEMEIN GW AJA LAH SI IAN KASE...,1.840000e+18,https://pbs.twimg.com/media/GXmxv2Ca8AAxId4.png,NaN,in,Sinful Circus,0,0,0,https://x.com/nocturnal_clown/status/183569386...,4.160668e+08,nocturnal_clown,9/16/2024 14:54,NaN
1998,1.830000e+18,Tue Aug 20 22:35:02 +0000 2024,0,eemang paling enak tuh nyelak di antrian tj,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/ndaradasihi/status/1826025174787...,1.670000e+18,ndaradasihi,8/20/2024 22:35,NaN

In [ ]:
# Remove tweets that contain "TJ Watt" (case insensitive)
df = df[~df['full_text'].str.contains("naik rute", case=False, na=False)]

# View the updated DataFrame
df

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
0,1.860000e+18,Sun Dec 01 14:34:21 +0000 2024,2,@PT_Transjakarta jadi buat besok kalau naik dr...,1.860000e+18,NaN,PT_Transjakarta,in,NaN,0,1,0,https://x.com/idlvsaygty/status/18632301591361...,1.540000e+18,idlvsaygty,12/1/2024 14:34,NaN
1,1.820000e+18,Sun Aug 11 07:43:40 +0000 2024,0,Gw tiap naik busway liat org make keyring truz...,1.820000e+18,NaN,NaN,in,𝖧𝗈𝗆𝗈𝗉𝗁𝗈𝖻𝗂𝖼 𝖽𝗇𝗂,0,0,0,https://x.com/cheershby/status/182253936505219...,1.410000e+18,cheershby,8/11/2024 7:43,NaN
2,1.840000e+18,Fri Sep 20 02:27:01 +0000 2024,0,Ampe kantor jam brp ini gue yaAllah ngestuck. ...,1.840000e+18,https://pbs.twimg.com/media/GX4odu4aQAAoz_1.jpg,NaN,in,Jakarta,0,0,0,https://x.com/joshonlee/status/183695519124726...,1.238640e+08,joshonlee,9/20/2024 2:27,NaN
3,1.870000e+18,Mon Dec 30 17:30:34 +0000 2024,0,⠀⠀⠀ &amp;. Anyway busway saya izin menyelam be...,1.870000e+18,NaN,NaN,in,1996. SFW. BIL (ENG/ID),0,0,0,https://x.com/InFortnight/status/1873783751718...,8.750000e+17,InFortnight,12/30/2024 17:30,NaN
4,1.820000e+18,Sun Aug 11 02:31:28 +0000 2024,0,Pdhl klen bisa menyulap tj mnjadi tayo bang bu...,1.820000e+18,NaN,NaN,in,mainly day6 riize txt,0,0,0,https://x.com/qohpisusu/status/182246079920356...,7.200000e+17,qohpisusu,8/11/2024 2:31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1.820000e+18,Mon Aug 05 02:47:47 +0000 2024,0,Hari hari depan halte busway https://t.co/iShF...,1.820000e+18,https://pbs.twimg.com/media/GUL4oKSWwAAR39O.jpg,NaN,in,"Swift Current, Saskatchewan",0,1,0,https://x.com/fyzlnrzl/status/1820290578363654199,2.646772e+08,fyzlnrzl,8/5/2024 2:47,NaN
1995,1.810000e+18,Mon Jul 01 02:19:21 +0000 2024,1,Pagi-pagi di busway otw kantor topup di @raide...,1.810000e+18,https://pbs.twimg.com/media/GRXid38a0AEzSyq.jpg,NaN,in,NaN,1,0,1,https://x.com/oceiann/status/1807599847677239461,1.310000e+18,oceiann,7/1/2024 2:19,NaN
1996,1.850000e+18,Mon Nov 04 11:32:27 +0000 2024,0,BENTAR HAO GUE MASIH DI BUSWAY,1.850000e+18,NaN,NaN,in,한빈.하오.규빈,0,0,0,https://x.com/bumblebeeen/status/1853399910223...,2.602640e+09,bumblebeeen,11/4/2024 11:32,NaN
1997,1.840000e+18,Mon Sep 16 14:54:58 +0000 2024,0,TJ ASTAGFIRULLAH SEMEIN GW AJA LAH SI IAN KASE...,1.840000e+18,https://pbs.twimg.com/media/GXmxv2Ca8AAxId4.png,NaN,in,Sinful Circus,0,0,0,https://x.com/nocturnal_clown/status/183569386...,4.160668e+08,nocturnal_clown,9/16/2024 14:54,NaN
1998,1.830000e+18,Tue Aug 20 22:35:02 +0000 2024,0,eemang paling enak tuh nyelak di antrian tj,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/ndaradasihi/status/1826025174787...,1.670000e+18,ndaradasihi,8/20/2024 22:35,NaN

In [ ]:
# Remove tweets that contain "TJ Watt" (case insensitive)
df = df[~df['full_text'].str.contains("hai kak", case=False, na=False)]

# View the updated DataFrame
df

,conversation_id_str,created_at_original,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,created_at_formated,Unnamed: 16
0,1.860000e+18,Sun Dec 01 14:34:21 +0000 2024,2,@PT_Transjakarta jadi buat besok kalau naik dr...,1.860000e+18,NaN,PT_Transjakarta,in,NaN,0,1,0,https://x.com/idlvsaygty/status/18632301591361...,1.540000e+18,idlvsaygty,12/1/2024 14:34,NaN
1,1.820000e+18,Sun Aug 11 07:43:40 +0000 2024,0,Gw tiap naik busway liat org make keyring truz...,1.820000e+18,NaN,NaN,in,𝖧𝗈𝗆𝗈𝗉𝗁𝗈𝖻𝗂𝖼 𝖽𝗇𝗂,0,0,0,https://x.com/cheershby/status/182253936505219...,1.410000e+18,cheershby,8/11/2024 7:43,NaN
2,1.840000e+18,Fri Sep 20 02:27:01 +0000 2024,0,Ampe kantor jam brp ini gue yaAllah ngestuck. ...,1.840000e+18,https://pbs.twimg.com/media/GX4odu4aQAAoz_1.jpg,NaN,in,Jakarta,0,0,0,https://x.com/joshonlee/status/183695519124726...,1.238640e+08,joshonlee,9/20/2024 2:27,NaN
3,1.870000e+18,Mon Dec 30 17:30:34 +0000 2024,0,⠀⠀⠀ &amp;. Anyway busway saya izin menyelam be...,1.870000e+18,NaN,NaN,in,1996. SFW. BIL (ENG/ID),0,0,0,https://x.com/InFortnight/status/1873783751718...,8.750000e+17,InFortnight,12/30/2024 17:30,NaN
4,1.820000e+18,Sun Aug 11 02:31:28 +0000 2024,0,Pdhl klen bisa menyulap tj mnjadi tayo bang bu...,1.820000e+18,NaN,NaN,in,mainly day6 riize txt,0,0,0,https://x.com/qohpisusu/status/182246079920356...,7.200000e+17,qohpisusu,8/11/2024 2:31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,1.820000e+18,Mon Aug 05 02:47:47 +0000 2024,0,Hari hari depan halte busway https://t.co/iShF...,1.820000e+18,https://pbs.twimg.com/media/GUL4oKSWwAAR39O.jpg,NaN,in,"Swift Current, Saskatchewan",0,1,0,https://x.com/fyzlnrzl/status/1820290578363654199,2.646772e+08,fyzlnrzl,8/5/2024 2:47,NaN
1995,1.810000e+18,Mon Jul 01 02:19:21 +0000 2024,1,Pagi-pagi di busway otw kantor topup di @raide...,1.810000e+18,https://pbs.twimg.com/media/GRXid38a0AEzSyq.jpg,NaN,in,NaN,1,0,1,https://x.com/oceiann/status/1807599847677239461,1.310000e+18,oceiann,7/1/2024 2:19,NaN
1996,1.850000e+18,Mon Nov 04 11:32:27 +0000 2024,0,BENTAR HAO GUE MASIH DI BUSWAY,1.850000e+18,NaN,NaN,in,한빈.하오.규빈,0,0,0,https://x.com/bumblebeeen/status/1853399910223...,2.602640e+09,bumblebeeen,11/4/2024 11:32,NaN
1997,1.840000e+18,Mon Sep 16 14:54:58 +0000 2024,0,TJ ASTAGFIRULLAH SEMEIN GW AJA LAH SI IAN KASE...,1.840000e+18,https://pbs.twimg.com/media/GXmxv2Ca8AAxId4.png,NaN,in,Sinful Circus,0,0,0,https://x.com/nocturnal_clown/status/183569386...,4.160668e+08,nocturnal_clown,9/16/2024 14:54,NaN
1998,1.830000e+18,Tue Aug 20 22:35:02 +0000 2024,0,eemang paling enak tuh nyelak di antrian tj,1.830000e+18,NaN,NaN,in,NaN,0,1,0,https://x.com/ndaradasihi/status/1826025174787...,1.670000e+18,ndaradasihi,8/20/2024 22:35,NaN

In [ ]:
df.to_csv("tweets_filtered_from_irrelevant_v1.1.csv", index=False)

: